# Generated by Django 3.0.5 on 2020-04-04 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('nutri_score', models.ImageField(db_index=True, upload_to='images/')),
                ('barcode', models.CharField(db_index=True, max_length=30)),
                ('picture', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nutri_score', models.ImageField(upload_to='images/')),
                ('barcode', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('nutrition', models.ImageField(upload_to='images/')),
                ('picture', models.ImageField(upload_to='images/')),
                ('composition', models.ManyToManyField(related_name='substitutes', to='catalog.Product')),
                ('user_sub', models.ManyToManyField(related_name='user_substitute', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
